name: Main repo workflow
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
      - name: Setup pipenv
        run: pip install pipenv
      - name: Instal dependencies
        run: pipenv install --dev
      - name: Black
        run: make check-black
      - name: Flake8
        run: make check-flake8
      - name: mypy
        run: make check-mypy
      - name: isort
        run: make check-isort
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
      - name: Setup pipenv
        run: pip install pipenv
      - name: Instal dependencies
        run: pipenv install --dev
      - name: Tests
        run: make run-tests-coverage
